export const factoryDesign = {
  name: 'Aster Microfactory Concept',
  product: 'Smart sensor pod',
  throughput: '480 units / shift',
  taktTime: '58 sec',
  floorSize: { width: 24, height: 14, unit: 'm' },
  machines: [
    {
      id: 'prep',
      name: 'Feedstock Prep Cell',
      type: 'Material Conditioning',
      status: 'Nominal',
      operator: '1 shared',
      cycleTime: 42,
      uptime: 96,
      energy: 4.8,
      footprint: { x: 1.2, y: 2.2, w: 4.1, h: 2.4 },
      inputs: ['Polymer pellets', 'Copper blanks'],
      outputs: ['Dried resin', 'Stamped contacts'],
      parameters: [
        ['Dryer temp', '74 °C'],
        ['Moisture target', '< 0.04%'],
        ['Blank feed rate', '68/min'],
      ],
    },
    {
      id: 'mold',
      name: 'Precision Molding Island',
      type: 'Forming',
      status: 'Optimizing',
      operator: 'Lights-out',
      cycleTime: 58,
      uptime: 93,
      energy: 18.2,
      footprint: { x: 7.1, y: 1.4, w: 4.6, h: 3.1 },
      inputs: ['Dried resin', 'Stamped contacts'],
      outputs: ['Overmolded shell'],
      parameters: [
        ['Clamp force', '120 ton'],
        ['Mold temp', '62 °C'],
        ['Cavity count', '4-up'],
      ],
    },
    {
      id: 'pcb',
      name: 'Electronics Assembly Cell',
      type: 'SMT + Micro Assembly',
      status: 'Nominal',
      operator: '1 technician',
      cycleTime: 51,
      uptime: 97,
      energy: 9.6,
      footprint: { x: 13.4, y: 1.8, w: 4.5, h: 2.8 },
      inputs: ['Bare PCB', 'MEMS sensor', 'Battery tab'],
      outputs: ['Testable PCB stack'],
      parameters: [
        ['Placement accuracy', '±18 µm'],
        ['Reflow profile', 'Lead-free 5-zone'],
        ['AOI sampling', '100%'],
      ],
    },
    {
      id: 'assembly',
      name: 'Robotic Final Assembly',
      type: 'Assembly',
      status: 'Nominal',
      operator: '1 shared',
      cycleTime: 55,
      uptime: 95,
      energy: 7.4,
      footprint: { x: 9.2, y: 7.1, w: 4.8, h: 3.2 },
      inputs: ['Overmolded shell', 'Testable PCB stack', 'Gasket'],
      outputs: ['Sealed sensor pod'],
      parameters: [
        ['Robot reach', '900 mm'],
        ['Adhesive bead', '0.42 mm'],
        ['Torque control', '±3%'],
      ],
    },
    {
      id: 'test',
      name: 'Validation & Packout',
      type: 'Test + Packaging',
      status: 'Nominal',
      operator: '1 inspector',
      cycleTime: 47,
      uptime: 98,
      energy: 3.1,
      footprint: { x: 17.1, y: 7.3, w: 4.1, h: 3.0 },
      inputs: ['Sealed sensor pod'],
      outputs: ['Finished and serialized product'],
      parameters: [
        ['Leak decay', '< 0.12 kPa/min'],
        ['Calibration points', '9-axis'],
        ['Pack format', '12 tray carton'],
      ],
    },
  ],
  flow: [
    {
      id: 'feedstock',
      title: 'Condition feedstock',
      state: 'Stable raw materials',
      detail: 'Resin is dried, contacts are blanked, and incoming lots are staged against the takt plan.',
      visual: '◌',
    },
    {
      id: 'form',
      title: 'Form product shell',
      state: 'Overmolded enclosure',
      detail: 'Contacts are insert-molded into a rugged polymer shell with traceable cavity data.',
      visual: '⬡',
    },
    {
      id: 'electronics',
      title: 'Build electronics core',
      state: 'Functional PCB stack',
      detail: 'Sensors, power tabs, and firmware identity are assembled and optically inspected.',
      visual: '▣',
    },
    {
      id: 'seal',
      title: 'Seal final assembly',
      state: 'Environmental pod',
      detail: 'Robot places the PCB stack, dispenses gasket adhesive, and closes the pod.',
      visual: '◈',
    },
    {
      id: 'validate',
      title: 'Validate and pack',
      state: 'Finished tested product',
      detail: 'Leak, calibration, communications, and serialization checks release units to packout.',
      visual: '◆',
    },
  ],
  flowLinks: [
    ['prep', 'mold'],
    ['prep', 'pcb'],
    ['mold', 'assembly'],
    ['pcb', 'assembly'],
    ['assembly', 'test'],
  ],
  renderProfiles: [
    {
      id: 'overview',
      title: 'Factory overview',
      camera: '24 mm wide angle, 1.6 m operator eye height',
      lighting: 'soft overhead grid with cyan flow accents',
      materials: 'brushed aluminum, matte black fixtures, polished concrete',
      subject: 'all five workcells, aisles, safety envelopes, and animated product-flow traces',
    },
    {
      id: 'assembly-hero',
      title: 'Assembly hero shot',
      camera: '70 mm lens, shallow depth of field, three-quarter view',
      lighting: 'warm key light with cool robotic-cell rim light',
      materials: 'ceramic grippers, transparent guard panels, satin polymer product shell',
      subject: 'robot placing the electronics stack and sealing a smart sensor pod',
    },
    {
      id: 'transformation',
      title: 'Transformation sequence',
      camera: 'orthographic exploded product-state composition',
      lighting: 'studio gradient with crisp contact shadows',
      materials: 'raw resin, stamped copper, populated PCB, gasket adhesive, serialized carton',
      subject: 'feedstock through validated packaged product in five states',
    },
  ],
};

export const machineLibrary = [
  {
    id: 'markforged-metal-x',
    name: 'Markforged Metal X',
    category: 'Metal 3D Printer',
    type: 'Bound-powder metal AM',
    source: 'Markforged Metal X system',
    sourceUrl: 'https://www-objects.markforged.com/craft/3d_printers_detail/metal-x/Metal_System_Datasheets.pdf',
    why: 'Accessible in-house metal parts for tooling, fixtures, and low-volume functional components.',
    cycleTime: 180,
    energy: 2.4,
    footprint: { w: 2.0, h: 1.4 },
    inputs: ['Bound metal filament', 'Wash fluid'],
    outputs: ['Green metal parts'],
    parameters: [
      ['Build volume', '300 × 220 × 180 mm'],
      ['Materials', '17-4PH, copper, Inconel'],
      ['Post process', 'Wash + sinter'],
    ],
  },
  {
    id: 'desktop-metal-shop',
    name: 'Desktop Metal Shop System',
    category: 'Metal 3D Printer',
    type: 'Metal binder jet',
    source: 'Desktop Metal Shop System class',
    sourceUrl: 'https://www.desktopmetal.com/products/shop',
    why: 'Batch-friendly binder jetting option for job-shop style short-run metal production.',
    cycleTime: 240,
    energy: 3.8,
    footprint: { w: 2.8, h: 1.8 },
    inputs: ['Metal powder', 'Binder'],
    outputs: ['Depowdered green parts'],
    parameters: [
      ['Process', 'Single-pass binder jet'],
      ['Best use', 'Small metal batches'],
      ['Post process', 'Cure + sinter'],
    ],
  },
  {
    id: 'sodick-aln400g',
    name: 'Sodick ALN400G',
    category: 'Wire EDM',
    type: 'Linear-motor wire EDM',
    source: 'Sodick ALN400G',
    sourceUrl: 'https://sales.sodick.com/products/wire-edm/aln400g',
    why: 'High-precision wire EDM for tooling inserts, fine slots, and hard-metal features.',
    cycleTime: 210,
    energy: 5.5,
    footprint: { w: 2.6, h: 2.2 },
    inputs: ['Hardened blanks', 'Brass wire'],
    outputs: ['Precision cut metal parts'],
    parameters: [
      ['Travel class', '400 mm work zone'],
      ['Drive', 'Rigid linear motor'],
      ['Strength', 'Precision + finish'],
    ],
  },
  {
    id: 'makino-u3-heat',
    name: 'Makino U3 H.E.A.T.',
    category: 'Wire EDM',
    type: 'High-accuracy wire EDM',
    source: 'Makino U-series wire EDM',
    sourceUrl: 'https://www.makino.com/wire-edm/',
    why: 'Compact high-accuracy EDM for die details, medical components, and additive-part cutoff.',
    cycleTime: 195,
    energy: 5.2,
    footprint: { w: 2.7, h: 2.3 },
    inputs: ['Tool steel blanks', 'EDM wire'],
    outputs: ['Fine-featured components'],
    parameters: [
      ['Machine class', 'U3 compact wire EDM'],
      ['Capability', 'Surface finish + accuracy'],
      ['Automation', 'Auto wire threading'],
    ],
  },
  {
    id: 'haas-mini-mill',
    name: 'Haas Mini Mill',
    category: 'CNC Mill',
    type: 'Compact vertical machining center',
    source: 'Haas compact / mini mill family',
    sourceUrl: 'https://www.haascnc.com/machines/vertical-mills/compact-mills.html',
    why: 'Common small-footprint VMC for aluminum, plastics, tooling plates, and prototype parts.',
    cycleTime: 120,
    energy: 6.8,
    footprint: { w: 2.5, h: 2.4 },
    inputs: ['Billet stock', 'Cutting tools'],
    outputs: ['Machined components'],
    parameters: [
      ['Travel class', 'Mini VMC'],
      ['Tooling', 'Automatic tool changer'],
      ['Best use', 'Shop-floor prototyping'],
    ],
  },
  {
    id: 'tormach-1100mx',
    name: 'Tormach 1100MX',
    category: 'CNC Mill',
    type: 'Bench-scale CNC mill',
    source: 'Tormach 1100MX',
    sourceUrl: 'https://knowledgebase.tormach.com/1100mx/about-your-machine',
    why: 'Accessible CNC milling platform suited to education, labs, and lean prototype cells.',
    cycleTime: 135,
    energy: 4.6,
    footprint: { w: 2.1, h: 2.0 },
    inputs: ['Aluminum stock', 'End mills'],
    outputs: ['Prototype machined parts'],
    parameters: [
      ['Control', 'PathPilot'],
      ['Spindle class', 'BT30 option'],
      ['Best use', 'Lab-scale CNC'],
    ],
  },
];

export function designMetrics(design = factoryDesign) {
  const machineCount = design.machines.length;
  const averageUptime = design.machines.reduce((sum, machine) => sum + machine.uptime, 0) / machineCount;
  const totalEnergy = design.machines.reduce((sum, machine) => sum + machine.energy, 0);
  const bottleneck = design.machines.reduce((slowest, machine) =>
    machine.cycleTime > slowest.cycleTime ? machine : slowest
  );

  return {
    machineCount,
    averageUptime: Number(averageUptime.toFixed(1)),
    totalEnergy: Number(totalEnergy.toFixed(1)),
    bottleneck: bottleneck.name,
  };
}

export function renderPrompt(profile, design = factoryDesign) {
  return `Photorealistic industrial microfactory render for ${design.product}: ${profile.subject}. Camera: ${profile.camera}. Lighting: ${profile.lighting}. Materials: ${profile.materials}. Include credible ${design.floorSize.width}m x ${design.floorSize.height}m scale, clean cable routing, safety markings, and premium manufacturing-detail realism.`;
}
